### ISSUE TITLE
Incompatible versions of nosto/nosto-magento and nosto/php-sdk in release 2.6.15.1

### ISSUE THREAD

**Issue by welou** [Nosto/nosto-magento-nodeps#1]
New constants are used in Nosto_Tagging_Model_Meta_Product. Constants are defined in the SDK in NostoProductInterface. The release 2.6.15.1 of nosto/nosto-magento-nodeps includes version 1.15.0 of nosto/php-sdk which does not contain the new constants.

Using the release 2.6.15.1 will crash Magento at least on product pages. I did not investigate further, but it appears that either too new code was included from nosto/nosto-magento or too old version of nosto/php-sdk is used.

**Comment by fairlane** [comment]
Thanks for reporting this @welou. I bumped the SDK version. Can you give it another try and let me know if it works for you project now.  The fix is in tag 2.6.15.2

**Comment by welou** [comment]
Thanks! Tested on our instances and everything seems to be in order now.

**Comment by fairlane** [comment]
Good stuff! Closing this one
